import type { NextPage } from 'next'
import Head from 'next/head'
import { sprinklesTailwind as st, clickable } from '../styles/sprinkles.css';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className = {
        st({
          background: {
            desktop: "orange-5",
            tablet: "red-5",
            mobile: "yellow-5"
          }
        })
      }>
        <h1>Olá, mundo</h1>
      </main>

    </div>
  )
}

export default Home
